APIError: cause property is now an Error and add meta property.
Having all the gdax-trading-toolkit specific Error subclasses have a
consistent type for the cause property is very useful. To replace the
use of the cause property with non-Error instances add an optional
meta property.