HTTPError: add an Error cause property.
HTTPErrorMessage's cause property is now the meta property. This will
allow the cause to turn into an Error later, for exception chaining.