Packages upgrade and prune them (#183)
* Bump typescript to ^2.7.2.

* Bump ts-node to ^5.0.1.

* DataFeed.ts: fix tslint 5.9.1 error.

ERROR: 260:16  whitespace  invalid whitespace

* Bump tslint to ^5.9.1.

* Remove unused @types/uuid and uuid dependencies.

Run

  $ yarn remove @types/uuid
  $ yarn remove uuid

* Upgrade @types/winston to 2.3.8 to match winston 2.3.0.