getSubscribedFeeds(): fix error when tsc compiles in strict mode.
src/factories/poloniexFactories.ts(48,64): error TS2345: Argument of type 'typeof PoloniexFeed' is not assignable to parameter of type 'ExchangeFeedConstructor<PoloniexFeed, ExchangeFeedConfig>'.
  Types of parameters 'config' and 'config' are incompatible.
    Type 'ExchangeFeedConfig' is not assignable to type 'PoloniexFeedConfig'.
      Property 'tickerChannel' is missing in type 'ExchangeFeedConfig'.