Upgrade to bignumber.js 4.0.4 and use its builtin types.
Run:
  $ yarn upgrade -E bignumber.js@4.0.4
  $ yarn remove @types/bignumber.js

Fix this warning:

src/lib/BigArray.ts(135,20): error TS7017: Element implicitly has an 'any' type because type 'BigNumber' has no index signature.